### ISSUE TITLE
Pull region and cluster id from machines CR

### ISSUE THREAD

**Issue by jewzaam** [lisa/docker-yq-kubectl#2]
Just dropping it here so it's tracked, we talked about the configmap going away.
Ideally we grab the region and cluster id from `infrastructures.config.openshift.io` but it's not a thing right now.
Until then, machines CR has both.
Note on EC2 instances `clusterid` tag can be expected to change eventually to `config.openshift.io` something but it's not there yet.

The `clusterdeployment.hive.openshift.io` has `infraID` which correlates to the EC2 tag `clusterid`.  It is not the object name or `name` in the CR's `spec`.

**Comment by jewzaam** [comment]
Oh, on not breaking when `clusterid` tag changes, recommendation is:

"get yourself covered by e2e-aws so we fail in CI if we forget to update you"

**Comment by lisa** [comment]
#4 addresses this. I've tried to make the shell script flexible for the future (although perhaps not as much as it will need to be).

**Comment by lisa** [comment]
#4 closes this.
